### PR TITLE
assignment one switched to junit demo

### PR DESCRIPTION
**Pull request by BradyRx7**

### CODE REVIEW

**Comment by smarks** [comment]
Hi, 
I am not seeing the DI here. Please review this week's chat and if you have any questions or would like to chat more schedule some 1:1 with me.

**Comment by BradyRx7** [comment]
I am going to try using the junit test class you provided. it just seems like a better idea since i definitely will need some pointers. Im going to create a new draft pull request for you to comment on

**Comment by BradyRx7** [comment]
Oops i closed it with the new commits from junit demo, my bad

**Comment by BradyRx7** [comment]
I ran maven and it was successful with 6 tests passed. But I did very little modification from the original junit test app you created. all i really did was run maven and edit the pom. the DI seems to be present in the junit test class already? Am i mistaken? If this needs additional edits to the junit test subscription classes please let me know! Thank you!

**Comment by BradyRx7** [comment]
maven tests for junit test class 9-18-19
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running edu.bradyreed.advancedjava.weekone.SubscriptionPeriodTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.041 sec
Running edu.bradyreed.advancedjava.weekone.SubscriptionTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.912 s
[INFO] Finished at: 2019-09-18T12:01:47-04:00
[INFO] ------------------------------------------------------------------------

**Pull request merged**
